server:
  port: 8080
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus      
  metrics:
    export:
      prometheus:
        enabled: true